on: [push, pull_request]
name: CI
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          check-latest: true
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Test
        run: go test -v -race ./...
      - name: Calculate coverage
        run: go test -v -covermode=count -coverprofile=coverage.out
      - name: Convert coverage.out to coverage.lcov
        uses: jandelgado/gcov2lcov-action@v1.0.9
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov
      - name: Run go vet
        continue-on-error: true
        run: go vet ./...
