on: [push, pull_request]
name: CI
jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
    # Prepare
    - name: Install Go 1.18
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - name: Checkout repository
      uses: actions/checkout@v2

    # TESTS

    # Run all tests
    - name: Test
      run: go test -v -race ./...

    # TEST COVERAGE

    - name: Calculate coverage
      run: |
        go test -v -covermode=count -coverprofile=coverage.out
    - name: Convert coverage.out to coverage.lcov
      uses: jandelgado/gcov2lcov-action@v1.0.6
    - name: Coveralls
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.github_token }}
        path-to-lcov: coverage.lcov

    # LINT

    # Install golangci-lint
    - name: Install golangci-lint
      run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.45.2

    # go vet
    - name: go vet
      continue-on-error: true
      run: go vet ./...

    # golangci-lint
    - name: golangci-lint
      continue-on-error: true
      run: golangci-lint run ./...
